name: Build Android App

on:
  push:
    branches:
      - main  # или любая другая ветка, которую вы используете для разработки
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: "adopt"  # или другая версия Java, совместимая с вашим проектом

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install --upgrade pip
          pip3 install buildozer
          pip3 install kivy 
          pip3 install kivy_garden.mapview 
          pip3 install pillow 
          pip3 install babel
          pip install cython

      - name: Build the project
        run: |
          cd .github/workflows  # замените на путь к вашей директории
          buildozer -v android debug

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-debug-apk
          path: .github/workflows/bin/*.apk  # замените на путь к вашему APK, если необходимо
