name: Build APK

on:
  push:
    branches:
      - main  # или ваша ветка

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: "adopt"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-setuptools git
          pip3 install --upgrade pip 
          pip3 install buildozer
          pip3 install kivy
          pip install sqlite3
          pip3 install kivy_garden.mapview
          pip3 install pillow
          pip3 install babel

      - name: Install additional dependencies
        run: |
          sudo apt install -y zipalign
          sudo apt install -y openjdk-8-jdk

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: bin/*.apk
